<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sign in</name>
   <tag></tag>
   <elementGuidId>ee8561a7-9f0f-44a2-a961-fee2b54427b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ladda-button.btn.btn-success.btn-sm.login-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>95b48cf7-5f48-431b-8802-3e82574c41e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9533bff8-bc66-46f5-b627-5d7803454891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ladda-button btn btn-success btn-sm login-button</value>
      <webElementGuid>1c9dc853-b58e-463e-93a9-1b861ac1195f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>submit()</value>
      <webElementGuid>24d8f658-18fc-43bc-a2a2-fdc99c2aab69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>gonogosignin.$invalid </value>
      <webElementGuid>d2b3edbf-37e3-416e-a321-678fe11434ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-style</name>
      <type>Main</type>
      <value>zoom-in</value>
      <webElementGuid>042d60ea-d4fb-4347-924d-c9bd4ebd83a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-size</name>
      <type>Main</type>
      <value>s</value>
      <webElementGuid>95d2a47f-6875-45e3-a9ad-b0e0915869ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ladda-button</name>
      <type>Main</type>
      <value>loginLoading</value>
      <webElementGuid>fda9106c-a0d0-4875-b12f-bad89799584c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-spinner-size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>8756c9e2-688b-4672-80ef-ecc2155d8cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>80d77209-7201-4724-a839-aeb4130e62cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fd68d9d3-32f3-4073-ba02-32d8af517c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Sign in</value>
      <webElementGuid>64c3f1ab-c52c-43fe-9557-4372253ab4e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;form-views&quot;]/div[@class=&quot;page-signin&quot;]/div[@class=&quot;signin-body&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;form-container&quot;]/div[@id=&quot;forget_password&quot;]/div[@class=&quot;panel-body&quot;]/form[@class=&quot;form-horizontal form-validation ng-dirty ng-valid-parse ng-valid-minlength ng-valid ng-valid-required&quot;]/div[@class=&quot;form-group last&quot;]/div[@class=&quot;col-sm-offset-4 col-sm-5&quot;]/button[@class=&quot;ladda-button btn btn-success btn-sm login-button&quot;]</value>
      <webElementGuid>c1618719-6314-4964-a962-0b38540e79cb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>1dec20e4-f0df-4280-aec7-b9428b1f8aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forget_password']/div[2]/form/div[5]/div/button</value>
      <webElementGuid>227c856e-9e4c-4ad7-b041-40d4d16e7eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remember me'])[1]/following::button[1]</value>
      <webElementGuid>251a8c18-056b-4c6a-b813-7a1332137084</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institution'])[1]/following::button[1]</value>
      <webElementGuid>6492904e-585e-4d9e-8934-992b1141b9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Password?'])[1]/preceding::button[1]</value>
      <webElementGuid>7009f8be-2e81-4c68-a084-56589e2cad48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0d2b6522-2e8f-4961-a497-9bf3db871633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = ' Sign in' or . = ' Sign in')]</value>
      <webElementGuid>2b4ecda3-7331-45eb-8d86-493466f82675</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
