<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PRODUCT_actionBtn</name>
   <tag></tag>
   <elementGuidId>b2fa42f9-4b64-4131-9db0-0841e3a54714</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='productlistTable']/tbody/tr[6]/td[9]/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(6) > td:nth-of-type(9) > div > button.actionBtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c68e1ad6-e871-4a24-95b0-e9a7137ee414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>actionBtn</value>
      <webElementGuid>5239ef17-2838-43eb-ada1-ace4df2f499b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>AddNewProduct('EDIT',item)</value>
      <webElementGuid>239e02ef-01dd-43f5-8e25-7db769097caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>e8dc820b-1155-48ed-9542-a56039e4f231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-if</name>
      <type>Main</type>
      <value>can('PRODUCT_UPDATE')</value>
      <webElementGuid>05ce542b-3f9b-46cd-a5d4-ddddb9e0a80f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>11e57033-93ad-49f2-bffa-078500fb6245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productlistTable&quot;)/tbody[1]/tr[6]/td[9]/div[1]/button[@class=&quot;actionBtn&quot;]</value>
      <webElementGuid>bb310821-3f78-4e2c-a18f-eff499759dcb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='productlistTable']/tbody/tr[6]/td[9]/div/button</value>
      <webElementGuid>325fca78-02ee-43a4-8d46-941e9c00436f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRODUCT'])[1]/following::button[1]</value>
      <webElementGuid>daa00cac-918a-4b1e-8c10-e6ba821e929f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RTWERCWEWER'])[1]/following::button[1]</value>
      <webElementGuid>79d41e06-64df-4444-9f90-01ffdbcca04f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTO'])[1]/preceding::button[1]</value>
      <webElementGuid>52ae505a-58dd-4d6a-90dd-f15a70bec0f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[9]/div/button</value>
      <webElementGuid>600db572-f99e-49f7-8af7-142b63d70f30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Edit']</value>
      <webElementGuid>ab351c01-5a0d-44db-8171-85073d2764c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
