<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FBL_SUPER_ADMIN</name>
   <tag></tag>
   <elementGuidId>569dbacf-58ce-44eb-9724-2724014dec6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/a/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.profile-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bc41689f-fbee-4fad-b9bd-897ef007b1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-info</value>
      <webElementGuid>989d2e03-34d8-47da-a0f1-2012d0f0ccd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FBL_SUPER_ADMIN  </value>
      <webElementGuid>c96b9fa4-303e-42c8-af74-3100221af9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;profile-menu&quot;]/a[1]/div[@class=&quot;profile-info&quot;]</value>
      <webElementGuid>3f079f65-ac70-4187-9135-20e98560839d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/a/div[2]</value>
      <webElementGuid>b4219d96-8a26-47a2-93fd-96124d067a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Fullscreen'])[1]/following::div[6]</value>
      <webElementGuid>942ccf3f-1873-414d-8586-b083f10f7ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAM Admin'])[1]/following::div[7]</value>
      <webElementGuid>a7a69557-2e8d-4507-8534-c03c029f8288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile View'])[1]/preceding::div[1]</value>
      <webElementGuid>7c23bb8b-fff1-446d-9a36-3bf10048182a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FBL_SUPER_ADMIN']/parent::*</value>
      <webElementGuid>1421427a-26ee-4024-b680-529ac372c780</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>44b7bf42-b80e-4eed-ba0c-f9130b8446f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' FBL_SUPER_ADMIN  ' or . = ' FBL_SUPER_ADMIN  ')]</value>
      <webElementGuid>486cf753-6acd-4715-b489-1b8979961bdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
