<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_UAM Admin_line center</name>
   <tag></tag>
   <elementGuidId>090fbfa7-45a7-40eb-9a35-cb85b6ad8949</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-trigger']/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.line.center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>441fe9dd-d10c-4ac6-bfae-f39120c0d70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>line center</value>
      <webElementGuid>eceb1ddb-0a8e-4d7a-9f5f-7d5c99806912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-trigger&quot;)/div[@class=&quot;line-wrap&quot;]/div[@class=&quot;line center&quot;]</value>
      <webElementGuid>9f5154e4-1839-4a65-bf63-4cf5488a48a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-trigger']/div/div[2]</value>
      <webElementGuid>71191119-9366-48c4-aba3-8a72f0f09fcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>c0e90683-5c55-4d44-8246-e2b100738d8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
