<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_HDFC_SUPER_ADMIN</name>
   <tag></tag>
   <elementGuidId>88611da4-379e-49de-8773-bd7fa57ab091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.profile-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mCSB_1_container']/div/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2be9e0bb-d53e-49da-baf2-6e07cfa2c483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-info</value>
      <webElementGuid>935b04bd-07f8-433a-8cfe-51cb7b387074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> HDFC_SUPER_ADMIN  </value>
      <webElementGuid>115c6867-1a5d-49b8-95a7-37f0356f691f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mCSB_1_container&quot;)/div[@class=&quot;profile-menu&quot;]/a[1]/div[@class=&quot;profile-info&quot;]</value>
      <webElementGuid>0aa824c0-0b72-4494-860b-a44596dd5cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mCSB_1_container']/div/a/div[2]</value>
      <webElementGuid>a7f03162-ec62-4de5-bc40-7cd4c6e180b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Fullscreen'])[1]/following::div[6]</value>
      <webElementGuid>aed92f8f-f918-4efa-a772-de8c457fb040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAM Admin'])[1]/following::div[7]</value>
      <webElementGuid>d998a199-34b9-41ec-a145-b838c33af3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profile View'])[1]/preceding::div[1]</value>
      <webElementGuid>c04421d4-4676-4e73-bd4f-afe9810f62a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HDFC_SUPER_ADMIN']/parent::*</value>
      <webElementGuid>a701756e-50c8-4a23-b5cc-c0b8e957b809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div[2]</value>
      <webElementGuid>0b6cb001-81b6-43a8-ba68-6a8fe8540f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' HDFC_SUPER_ADMIN  ' or . = ' HDFC_SUPER_ADMIN  ')]</value>
      <webElementGuid>95030190-edcf-4adf-af0f-9010e6133335</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
