<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_UAM Admin_menu-trigger</name>
   <tag></tag>
   <elementGuidId>9cda6f4f-6d4d-42c0-a702-c45613b6e891</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-trigger']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-trigger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>b6473663-73a5-422c-b0c1-3a805edb5ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu-trigger</value>
      <webElementGuid>4cc91198-7ee7-429e-90ea-cb5e378cf4c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>mainmenu</value>
      <webElementGuid>a1188b39-d1ad-4f47-a6b3-235abb09a862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-model-left</name>
      <type>Main</type>
      <value>mactrl.sidebarToggle.left</value>
      <webElementGuid>931f6f66-1d15-4826-bd49-b78c54f498c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ 'open': mactrl.sidebarToggle.left === true }</value>
      <webElementGuid>090f39c9-49ce-423f-8a22-0a103086a41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-trigger&quot;)</value>
      <webElementGuid>70a6119e-453f-40ef-806c-dbbe7f9fc0ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='menu-trigger']</value>
      <webElementGuid>b773168b-58e7-415f-8b72-b1d36928accc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/ul/li</value>
      <webElementGuid>6718785a-7f2a-422e-a168-b665c887f1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAM Admin'])[1]/preceding::li[1]</value>
      <webElementGuid>7991bfc7-9ea7-40ad-ae65-8af30ff70945</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Fullscreen'])[1]/preceding::li[5]</value>
      <webElementGuid>dbbd4a91-4bb2-43c9-83ee-589b4f944731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>a80ddfc9-7918-4b34-bcd2-fcbb6bd6d8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'menu-trigger']</value>
      <webElementGuid>b2c7872b-7082-4741-8ea5-f806477e9f25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
